language: node_js
node_js:
- 10.8.0
install:
- npm install
script:
- npm run build
- npm run test
deploy:
  skip_cleanup: true
  provider: script
  script: bash ./deploy.sh $TRAVIS_TAG
  on:
    tags: true
cache:
  directories:
  - "$HOME/.npm"
env:
  global:
  - secure: BG3c1QYv2JHNIFVusmsoQ20Fia97wI6Xw6/haN3qSdfRp+iwEQsvLBDb1g6GxDNdHstOCSGB4MrlSjMNXG4e2U+Q2cC3BPkWEsjmKf5JULsEtDSTlDHdFJJjIVKWHdP42ucR7ThS0skWuI7eLRNsrm2fh8FVkixH7UpNceij8O8Nc6t4gw0kcFVgJG3n2MDgYRj3itFX1hRoxgLcpRYoMGuvRIqnPJRAp5IcgZiUwBkJ60ZhGSvx9LRROMGifkU96NIVtXLazUQOD2d6N6jBKGFmrd3ADiZCmLX65rsTSEr0UIWi7132qPfw1HKcsK+B75tZH1yvFv6PcWD7SYg3ipaejicLroW8DT2wz+w1v1Fj7mjUTrPn5SHHoRhXrKXCi52kGex58Da3G/aU4RfRtcWjwMpzQ2mCr4ZWpnog50Zydh0jH0hQnpmxQBLAIkEslNrfMVv87dkX69KyE71z0WKO7NIwEoygABdSzY9l+ZnFFjoF2LFo59FPAEsHbNaoDUoB+sjnAd+I2ekwqVZWobqLTJ7CWYITflIpa9ysqmL0iPDvGteM/PO1uPd8+8rrlqTH3V2Ba5Qn7RQoqDIZtYUs56XO/mRYmSEfwNlKVDU/+d6qjgBzVyTZ75jHbS78KoDrKf40PwwYh42Lbq1ZLCYWeIjTkvo6BifKDhvlEdg=
  - secure: W8x9P52foDhT7AxlDHdwqRf0tIPjUJntA8dyD9DVDQTLd9WoSq1ahtZ3Ef75dvLkNEDULDJJvr2neUyw6RyJMBL1cnHiLJLHEhgnVnquIYrZ3DrYCNpfIbxvv3aibG8hdEKtpBzwPC2LdsUgj/DCOG/DPZF0dzKcx4qpBhmcbkb3GtSKiAQFsw/SaywzK697slzgjlHcxFQP7+CuB7kO789Hev7bAuk935FcCLS/Uq7e/7/LLJnqin6pfxhXuyilcfjvQAqiwqRPebNxljw5gho+HfQGgSLPHH8s5ZvlN2rxBkVYu83t+IoIyW5zF2kQpuXltUNfX+WcvC/jJtxh7nzGHtQdVsOvzMvoGPJK0HWBGD2syKCRO4Mltt3OaRVMHPeAugVJ5o579ek3zh1ea5DDt+ERXgi9eXVeDCvOoyLWxQwBU7cl3fUDUxjPhxv9U8l6pZEMsGemXpOJfhd2UMWYk4ZPLDQnyaktUYEjI5KDEnC7NVDgKVyR81AG1tOCGOXJSF7tJ7o5rQYPBbcUEFQVh4GXLFXdsLY65mcRl+JBphbFiCJv24yDVmSBKmwOmAq3AuXRuXqJOt8j40XziaUl6itbYqvN2jZJZbJUnqdWuWjEJa4D7+sQpfnzdsiItKmR8fMUFklI73KwkS++tTaDwRPo2A1cKRyyTXfpPqo=
