language: node_js
node_js:
- 10.8.0

install:
- npm install

script:
- npm run build
- npm run test

deploy:
  skip_cleanup: true
  provider: script
  script: "bash ./deploy.sh $TRAVIS_TAG"
  on:
    tags: true

cache:
  directories:
    - $HOME/.npm

env:
  global:
  - secure: YyNeuw9xZfnQo36c/TWDuMBkOURebUGgcH0x/2/QIOIA7zfLmU9I2JMNt1VxzZqeV0XUA9/vJVHoxk5uXRaPCIPRacILXqNwTjFpxKb6T9jbInR2ZeRUXvr57SduaIoyvVqX5sbBcu9ROPCw2qxdRcNrHjADJUYDu65LNfxT28vVxvIvAqDuTUiJHKAQI4TF5YiGKi0ay0sGLZvGT1gyaMG5BDtfnVsopX7325ModKcd0kW5f6JbEfl5h+J9MKQl/2ZsCm7cNt4qhcmZC2BpmgL6KPzPw4nB6hDnTr+rx7lhECbdRmS5h2PHH/v2oOyu1z5VFXCvw3Kwy226Px5E5SN5bh5x804A5c7UHpnburyAEzhcgBaNswuyiXw3m6YalNgWl7mtfesW01WRr69GOK5cwYsIJ6V2rzH0pQU4g4lSLsAypJ/4KAtjp/3F/++rs4PkyBy+t1x0BB2FfhV5ReM8E1LQeaZeC4aZYf8qfVHJLnJs6TmnmPAW0abw/WvIFAw9hK2ymEEoOR6cv6Fg66Rs3zhkb+VE/a6e84vpI+6F1wgjmIoqrUdJJIus1TPoicj+DE8ud3HanHgrD5V/wNeW5hglDoQJPycf9a4PCObffwzDEgztdQ+7mKopfXG4EmPU0dqVeq/ah7MLF5Hf07D7pbpEMAk0A/vU6DaXBic=
  - secure: P1yUN3XAwRIKDO2UCmO81Yevo0tfvoJQQPE/h3+ooJqALD0p8r0GgsKBFtnuhA8nWkbz6/XjWbzolRHwNzKnUk8A9i7la8SzSNGhBk5NgKtnjCjlfge3Gb+So1myuyuis+EnSbIiOXJU1ESyJsbD5stBuS2zToCOe6WKAyDRhW5GGp6xpt8CgjuhQ0DODqqynl1Y2QGaMfv8gt5MsMvKkMuXGRLOBkiMxeeta0vYwH4O3Y5IUTFiuuyASQK6rG0LCW4xIUxX+UWcr4Vej/qcrhO4wk77WDb2Qmj/L3cvKBdUYGl2DzQRP8U0SObtxDwiZTvjdGM/WvlgnsKf4cn09as68c3LebFIHreVQrfXx6qWLYDIFHmaXqQOSYC3ilNeveBvI/uL1tdiX8cXkrbDNu7QW/HFKhMh1rH94ulEpbXDgPGwfaIkr9Raw+elIVYngKn2bC66NJNLalvamHSNpykE3FCKIkFDcE4lU7oEFklS6BBCQBGG3ViEur+eDd+TVZMI14sFeFTBEYRAVd4if3Wo20ir2DtDzernVGPm9YRqU3j0Pu0OqAEoVxKk9M5dNSUrCjYPsMKBxWPRhGuV2eoEY31B7jmeqwzEeph4xEWn4N/02duppY8YbPPsgLi2nMugpAHutQZpUHG5deeKEEKme+XpKcagpQ3JBHa1d7s=
