language: node_js
node_js:
- 10.8.0
install:
- npm install
script:
- npm run build
- npm run test
deploy:
  skip_cleanup: true
  provider: script
  script: bash ./deploy.sh $TRAVIS_TAG
  on:
    tags: true
cache:
  directories:
  - "$HOME/.npm"
env:
  global:
  - secure: mzYol8/aKRufBz94dZFxvKk7l41IQNIcZKoSh1bX8R4lCKkvRAekLoM3LstLrmPJR8r0qsEOOorD4IgHxCqTF9VW05NsX1YWIbQcxTvrYx81Ct62cKK/xtKpHtAlyItx2HYPEn7zjC/9Ku4wBQo3fgaVgyCyO+7iQ8PDAC8t3RHkdpoWZUdAbP8lh1nVUquMM//XeQaEvEnre19C3UFuvJIQMgob+7E0TMNlCucyQ4iIxCdQ8iBDpeTIG3wL7HdbN85/NDNIweU2pxAMOX17x6Su0gAkTJicsjXu+A4ZH6dOJYKq4/GSxW2APLGFTbdekcxAlEA3vl0h7m0zuJi4PdEKj0hUf+klvT3rtjeNSUrW+FNMeWkuhQzYpJ7PVnugOnxEVxmk/1WMquStF73vX1TSFoAFYv2VfgQlYV2fx4lvHFXKmQE9k3/uRN6Wm613kSWR0GzFjLdPF9LcP1NeILJX+Lc2rGkcP+6rbIsnyAEfNI/Q4fd0E8HNMEIad6eGqO7+4ZmJ43apMkEeMvUr5fj/iEwtpoeUn08EbxZ3s5aoqp4m/qVblJG0fWlAAaNp3qw8NL8gXpBZf/wTofLPMyDt2e46oWConHnz9kb48TYDxYLyhBHvuHVyTzfuvazKRquLmaOaVfwfM1alwa11F4P9VNVFj4sZqVI+W555SqQ=
  - secure: k4wG51mSmsANTEzr3ZewRxTPt2D+vHPFavFqjq1h3hH2z/VUz/+07Z7lWDLWq5UUYdoUkMZbTn4vx8ET8nIgJoJMlq9SAD1LOo2i5V3x5DqU/ye07WmuQfLstDPO6aIYBGGP/b949+NVNr21xbO7i1YoNWAPeiwRswVKpQmGeuVfXp+FXqP9XOBbXxzd4c6fOhSocuQh+5dfmnzRWKaldi9D6RlmdLEUjls/WYY/+QFHRkC/lAgGBjJL8CsypvHUT/mEYgNhD1ipDdJy53IDoMqd3PWTwZ17Udl6k8CFC5U1F4PQ5tQQYP4HetKQqhB4P5kY6B5/80f5aLUnoB6mmDAVILbBNN5wusQqOTnWw+ytSvb7rkU2D19WUkSqmDDaxyZixLuIbajHGkitGaKkrJJSvpp7vO6RrFH0IZFF2soJ+mWk755VczAO/GXDqwlTOQ4pv+7fAVT61uqbu0WkKTM35DivCG3ovqPUf4rH7IY2tjPEPjWQd9gtBURfccZjeyNgnWDfrXxJ1JQMQQ8x4P6CQV/+uyS/gVXTGyfFAFizXnsWFAflTlIdiyb4zzj2ycJoYFxG5q5e3B/aCi1ygwnEq7MdynyUxU+vavA1Iwb12Ug2ycydfjTPDkClz17YGvZjMPmG6ksy1yPfCRgpisOwOyEluRewZwIgp5vKu4k=
