language: node_js
node_js:
- 10.8.0
install:
- npm install
script:
- npm run build
- npm run test
deploy:
  provider: npm
  on:
    tags: true
  api_key:
    secure: JMq/RouZkxKDdHzLPhHOJdKoO5/0NuI+eRMI38sN1stu/u5A+t4LoOjiFLxDezv9Vbna80BtR2SRmyDZIMXugIoMuapmYXWTa2gkaPmU8MThuwVQJK3MsdytjPeYuQbhsZNuLBchotoz6lSI68f1JNbvYSENkTMDQPoqMLDKm5haWtl+B5PyhT3Nr2HP4eevrrq/oPqAnR4vh40uuwnTkj2JQgEs6y9p81tS8ptq6HIgIU19Qp2yZP50M01hJTMpjUCMOjhfpKdvR6iagtkEWWMtzf07Me1JFNI1bO9L7DP/M8YGeoCejOrLrTvLl0GLVY3f1EkaAwY2CnkjhFL1SD/FJDP9lJNzw8oUj7cxQ6S5dQf4FCHvJUYW5d3ChxsBxeTppvacxna3G0N9Icnto/CVzYroKxAsb4Z27JXDSUNazCqA09F76JbeJJY4KhPtM76gWDbwehyp5kQ/D35CrxWn9vzrxRyq5aEk6n3zdhXf7/INLkOSZcG2N9+eBwp5y6s78SW+zIAWN/3yVi5K6Q3qHTW7yrqlMO8kLW7UEELzqpiwxlmxx3k8FNhifuSOjY6c+6XXUQ1t4CAU35Ho12L/QDL2aFELvf9VhACcfPYkCijsFBd1cXydTpSgB2M+mr4a2d0X5NOWypGa8USWAgZhlt7LbCm9OadwdGgCj0c=
  email:
    secure: caX+ParxOrXjWPa24XbZv7TaCxxoeBOzrpRvq011twyej3HqPc6k0UcwvpQf46a3zbrZ1bZqQf+3zoM+L86buGb/4hhA5wXL5wOA46jiTweItr1pT7y9Vw1Hzuc51c+oL3NR/hdJdLqlkn82iyzXBL9c4rE7Ty+yxQk16QrJbek2maDldyLCzZf4hToUL1V3ZFL4xEIONP7rcnSPPuE1xbotN2fPHEKOy2VDu4yd5ue+iO6izZodxbLAr0M6HLrmk65YGqXoCAcE3mn+fIZBkRke+4fdASLLecPoKRRiJJ3TvAtGTXNF5zd1/+n1vpfX0wnaZqq7+4RlGoDQI8ovAJLPwKt0cNxsWN0RrQv6nHh7EL8qtOfbW2ANleKEP4moalmxv2R+ufq12HntZS1x4YgI0F7NP4rkt103Ql/JV0NXmD7NoPm83G1XAbrr/yQfbGw0jjuNaNyNXxNWBa47kNh6YHqf9cymH8GewueMinaF0IVtUurTRN/itKBZ13M+MHzA2IFO8W1KAY51gnjsvdqpqlEINBJ9DwjT4nfty/LDVgkPJ4Z4GEbtuzLorSs2KqtFe7ZGoneyRE/wPql8HPNY3LtYEpGZOxgagQkKUO6vogVidTCAkJSuPqxmBnAmhNro2g/nu7M1Q0LhCa65T5hmc/ckIkA2VHYOp6cTC4s=
